### ISSUE TITLE
Plugin index has incorrect links

### ISSUE THREAD

**Issue by duckbrain** [chaijs/chaijs.github.io#166]
1. Go to plugin page
2. Click on a tile
3. Get a 404

At first the behavior seemed the same as #116, but then I realized the plugin pages use underscores instead of hyphens in their permalinks. The only plugin that does work is [chaid](http://www.chaijs.com/plugins/chaid/) because it has no hyphens.

The links should be to the permalinks or the permalinks should be changed to hyphens.

**Comment by duckbrain** [comment]
Changing to the hyphens would probably be better because Google seems to be linking to the hyphenated versions

https://www.google.com/search?q=chaijs+promise+rejects&ie=utf-8&oe=utf-8&client=firefox-b-1-ab

http://www.chaijs.com/plugins/chai-as-promised/

**Comment by keithamus** [comment]
Thanks for the issue @duckbrain! I hope to have fixed this in https://github.com/chaijs/chaijs.github.io/pull/167
