### ISSUE TITLE
Delist or update sinon-chai plugins (404)

### ISSUE THREAD

**Issue by Ryuno-Ki** [chaijs/chaijs.github.io#173]
When visiting http://www.chaijs.com/plugins/@cypress/sinon-chai/ or http://www.chaijs.com/plugins/@slightlytyler/sinon-chai/ I see a 404.

The corresponding markdown files can be found here:
https://github.com/chaijs/chaijs.github.io/blob/8cba8fe81a3c0cf2c9679691faed63d2ab4a4b81/plugins/_cypress_sinon_chai.md and https://github.com/chaijs/chaijs.github.io/blob/8cba8fe81a3c0cf2c9679691faed63d2ab4a4b81/plugins/_slightlytyler_sinon_chai.md.

Either @domenic and/or @slightlytyler updates the submission (see code in https://github.com/domenic/sinon-chai resp. https://github.com/slightlytyler/sinon-chai) or those plugins should be removed.

**Comment by keithamus** [comment]
We scrape npm for the plugin listing. We can manually blacklist plugins here: https://github.com/chaijs/chaijs.github.io/blob/master/_scripts/banned_plugins.js. I'll add these to the list of blacklisted plugins.

**Comment by keithamus** [comment]
Should be fixed in https://github.com/chaijs/chaijs.github.io/commit/24af0083ee0ec7bafe117fec4e9c09dd4e567575
