### ISSUE TITLE
DNS Issues?

### ISSUE THREAD

**Issue by jbutz** [chaijs/chaijs.github.io#175]
It looks like there may be some DNS issues with the website. Just wanted to make sure that was known.

![chai](https://user-images.githubusercontent.com/736696/45217435-0550d700-b272-11e8-8e18-d54a333a840e.PNG)

**Comment by keithamus** [comment]
Hey @jbutz thanks for the issue 

I'm unable to reproduce this. The DNS seems fine, https://mxtoolbox.com/SuperTool.aspx?action=a%3achaijs.com&run=toolpage and as the page itself says, the domain wont expire until 2019. @logicalparadox still has ownership.

Is there maybe an issue with your ISP perhaps? Could you try to reproduce using a different internet connection?

**Comment by jbutz** [comment]
The issue seems to have cleared up on my end.
