### ISSUE TITLE
All current browsers refuse to go to chaijs.com: Invalid certificate (HTTP is no longer allowed)

### ISSUE THREAD

**Issue by lll000111** [chaijs/chaijs.github.io#176]
The subject says it.

Firefox and Chrome seem to FORCE https now. manually attempting to load via `http://` does not work: https://security.googleblog.com/2018/02/a-secure-web-is-here-to-stay.html

> Beginning in July 2018 with the release of Chrome 68, Chrome will mark all HTTP sites as “not secure”.

Firefox:

> www.chaijs.com uses an invalid security certificate. The certificate is only valid for the following names: *.github.com, github.com, *.github.io, github.io Error code: 

> SSL_ERROR_BAD_CERT_DOMAIN

Chrome:

> This server could not prove that it is www.chaijs.com; its security certificate is from *.github.com. This may be caused by a misconfiguration or an attacker intercepting your connection.

When I try to proceed anyway (both FF and Chrome) I end up with

> This page isn’t working
> www.chaijs.com redirected you too many times.
> Try clearing your cookies.
> ERR_TOO_MANY_REDIRECTS

IE Edge: the same.

---

Possibly relevant: 

https://blog.github.com/2018-05-01-github-pages-custom-domains-https/#configuring-your-domain

**Comment by aaronsofaly** [comment]
@lll000111, thanks for the heads up!

We're currently loading JS and CSS assets with `http` absolute paths. So any forced redirects to `https` is going to throw a `Mixed Content` error. We have a PR open [here](https://github.com/chaijs/chaijs.github.io/pull/177) to have this fixed soon :)

**Comment by keithamus** [comment]
Looks like it's now all working fine on my end. Closing this. Thanks for the reports all 👍
