### ISSUE TITLE
Domain name expired

### ISSUE THREAD

**Issue by willrnch** [chaijs/chaijs.github.io#200]
<img width="937" alt="Screenshot 2021-12-16 at 12 24 10" src="https://user-images.githubusercontent.com/1873880/146363143-03603226-1e07-4e41-b860-045f2e5d93c4.png">

**Comment by keithamus** [comment]
Thanks for pointing this out @willrnch.

I've got in contact with @logicalparadox who still has ownership of the domain. Hopefully we can rectify this.

**Comment by keithamus** [comment]
I've removed the CNAME file so for now the site is accessible via https://chaijs.github.io/

Hopefully we'll get the domain name renewed and this will be solved.

**Comment by lionello** [comment]
> I've removed the CNAME file so for now the site is accessible via https://chaijs.github.io/
> 
> Hopefully we'll get the domain name renewed and this will be solved.

You should also change the URL on your GitHub profile to point to the GitHub pages one.

**Comment by willrnch** [comment]
I took the liberty of deploying it behind https://chaijs.dev/.

**Comment by willrnch** [comment]
But it seems that http://chaijs.com/ has been renewed.

**Comment by keithamus** [comment]
We’ve managed to renew the domain and point it back to the pages site. I’ll close this now. Thanks for everyones assistance here.
